apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  namespace: development
  labels:
    app: reference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reference-service
  template:
    metadata:
      labels:
        app: reference-service
    spec:
      containers:
        - name: reference-service
          image: reference-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
