apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development-environment
  namespace: argocd
spec:
  description: Namespace, resource policies, and access controls for the development environment
  sourceRepos:
    - https://github.com/Rano1000/internal-developer-platform.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: development
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
      name: development
  namespaceResourceWhitelist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
