apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-environment
  namespace: argocd
spec:
  project: development-environment
  source:
    repoURL: https://github.com/Rano1000/internal-developer-platform.git
    targetRevision: main
    path: platform/environments/development
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: false
