apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reference-service-development
  namespace: argocd
spec:
  project: development-workloads
  source:
    repoURL: https://github.com/Rano1000/internal-developer-platform.git
    targetRevision: main
    path: platform/environments/development/reference-service
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
