apiVersion: v1
kind: ResourceQuota
metadata:
  name: development-budget
  namespace: development
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "10"
